### ISSUE TITLE
Renderer: Retrieve Text from Document

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/typst.ts#6]
Implementing [Proposal 2, **Renderer**: Retrieve Text from Document][proposal-2-retrieve-text-from-document]

## Description

Replace the PDF text extraction algorithm by retrieving information from document accurately and efficiently.

To finish the task we need to implement the following function:

```rust
/// pdfJs.TextContentSource
pub struct TextContentSource;
pub fn reconstruct_text_information(&self, doc: &typst::doc::Document) -> TextContentSource;
```

## Task list

+ [x] Create proposal
+ [x] run `page.getTextContent()` and replace all text content by point mapping.
+ [x] remove use of `page.getTextContent()`
+ [x] remove use of `page.getViewport()`
+ [x] remove use of `pdf.getDocument`

[proposal-2-retrieve-text-from-document]: https://github.com/Myriad-Dreamin/typst.ts/blob/main/docs/proposals/2-retrieve-text-from-document.md

**Comment by Myriad-Dreamin** [comment]
done by https://github.com/Myriad-Dreamin/typst.ts/commit/47aeb7deb4966b10536ae9a44658e786e764092d
